=== over2sd/minette/dtd/person.dtd
<!ELEMENT abil ( #PCDATA ) >
<!ELEMENT age ( #PCDATA ) >
<!ELEMENT appear1ch ( #PCDATA ) >
<!ELEMENT appear1wr ( #PCDATA ) >
<!ELEMENT asmell ( #PCDATA ) >
<!ELEMENT attposs ( #PCDATA ) >
<!ELEMENT backstory ( #PCDATA ) >
<!ELEMENT bday ( #PCDATA ) >
<!ELEMENT bodytyp ( #PCDATA ) >
<!ELEMENT commonname ( #PCDATA ) >
<!ELEMENT conflict ( #PCDATA ) >
<!ELEMENT ctitle ( #PCDATA ) >
<!ELEMENT currocc ( pos, events? ) >
<!ELEMENT date ( #PCDATA ) >
<!ELEMENT dday ( #PCDATA ) >
<!ELEMENT dress ( #PCDATA ) >
<!ELEMENT ethnic ( #PCDATA ) >
<!ELEMENT event ( #PCDATA ) >
<!ELEMENT events ( mstone* ) >
<!ELEMENT mstone ( date, event, type? ) >
<!ELEMENT eyes ( #PCDATA ) >
<!ELEMENT fname ( #PCDATA ) >
<!ELEMENT formocc ( pos, events? ) >
<!ELEMENT gender ( #PCDATA ) >
<!ELEMENT hair ( #PCDATA ) >
<!ELEMENT hobby ( #PCDATA ) >
<!ELEMENT leadrel ( #PCDATA ) >
<!ELEMENT lname ( #PCDATA ) >
<!ELEMENT dmarks ( #PCDATA ) >
<!ELEMENT file (#CDATA ) >
<!ELEMENT mention ( #PCDATA ) >
<!ELEMENT minchar ( #PCDATA ) >
<!ELEMENT misc ( #PCDATA ) >
<!ELEMENT mname ( #PCDATA ) >
<!ELEMENT mole ( #PCDATA ) >
<!ELEMENT nname ( #PCDATA ) >
<!ELEMENT nameorder ( #CDATA ) >
<!ELEMENT origin ( #PCDATA ) >
<!ELEMENT other ( #PCDATA ) >
<!ELEMENT person ( commonname?, ctitle?, gname?, mname?, fname?, nname?, nameorder?, gender?, bday?, dday?, stories?, mention?, appear1ch?, appear1wr?, conflict?, leadrel?, bodytyp?, age?, skin?, eyes?, hair?, dmarks?, dress?, attposs?, asmell?, personality?, speech?, formocc?, currocc?, strength?, weak?, mole?, hobby?, misc?, ethnic?, origin?, backstory?, residence?, minchar?, talent?, abil?, sgoal?, other?, relat?, aspects?, update? ) >
<!ELEMENT personality ( #PCDATA ) >
<!ELEMENT pos ( #PCDATA ) >
<!ELEMENT relat ( related, relation, file?, rtype, events*, cat, realm? ) >
<!ELEMENT realm ( #PCDATA ) >
<!ELEMENT rname ( #PCDATA )>
<!ELEMENT cat ( #CDATA ) >
<!ELEMENT rtype ( #CDATA ) >
<!ELEMENT relation ( #PCDATA ) >
<!ELEMENT related ( #PCDATA ) >
<!ELEMENT residence ( #PCDATA ) >
<!ELEMENT sgoal ( #PCDATA ) >
<!ELEMENT skin ( #PCDATA ) >
<!ELEMENT speech ( #PCDATA ) >
<!ELEMENT stories ( #PCDATA ) >
<!ELEMENT strength ( #PCDATA ) >
<!ELEMENT talent ( #PCDATA ) >
<!ELEMENT type ( #PCDATA ) >
<!ELEMENT weak ( #PCDATA ) >
<!ELEMENT update ( #PCDATA )>
<!ELEMENT aspects ( text* )>
<!ELEMENT text ( #CDATA )>

=== over2sd/minette/realms/example/doe-jane.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="person.xsl"?>
<!DOCTYPE person SYSTEM "person.dtd">
<person>
	<commonname>Jane Doe</commonname>
  <ctitle>Mrs.</ctitle>
	<gname>Jane</gname>
	<fname>Doe</fname>
	<nname>Muffins</nname>
	<gender>F</gender>
	<bday>1978/7/8b</bday>
	<dday></dday>
	<stories>My Tale 2</stories>
	<mention>MT, ch 1, s 1</mention>
	<appear1ch>MT 2.2</appear1ch>
	<appear1wr>MT 2.2</appear1wr>
	<conflict></conflict>
	<leadrel>Wife</leadrel>
	<bodytyp>average height, average build</bodytyp>
	<age>39 (2017)</age>
	<skin>thin</skin>
	<eyes>brown, soft</eyes>
	<hair>brown</hair>
	<dmarks>star-shaped birthmark on her shoulder</dmarks>
	<dress>knee-length skirt and button-up blouse</dress>
	<attposs>a purse</attposs>
	<asmell>Orange Sable perfume</asmell>
	<personality>easy-going</personality>
	<speech></speech>
	<currocc><pos>Secretary of the Interior</pos><events><date>2000/1/1b</date><event>Appointed</event></events></currocc>
	<strength>patience</strength>
	<weak>color-blindness</weak>
	<mole>walks with a slight limp</mole>
	<hobby>singing, building thermonuclear devices</hobby>
	<misc></misc>
	<ethnic>islander</ethnic>
	<origin>Tin Island</origin>
	<backstory></backstory>
	<residence>a small apartment on 15th street</residence>
	<minchar>father</minchar>
	<talent>sewing</talent>
	<abil></abil>
	<sgoal>To finish the Times crossword puzzle</sgoal>
	<other></other>
	<relat>
		<related>John Doe</related>
		<relation>Husband</relation>
		<file>doe-john</file>
		<events>
			<mstone>
				<date>2005/1/2b</date>
				<event>Married</event>
			</mstone>
			<mstone>
				<date>2004/6/1b</date>
				<event>First date</event>
			</mstone>
		</events>
		<rtype>fam</rtype>
		<cat>person</cat>
	</relat>
</person>

=== over2sd/minette/realms/example/doe-john.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="person.xsl"?>
<!DOCTYPE person SYSTEM "person.dtd">
<person>
	<commonname>John Doe</commonname>
  <ctitle>Mr.</ctitle>
	<gname>John</gname>
	<fname>Doe</fname>
	<nname>Johnny</nname>
	<gender>M</gender>
	<bday>1977/1/1b</bday>
	<dday></dday>
	<stories>mt1,mt2</stories>
	<mention>MT, ch 1, s 1</mention>
	<appear1ch>MT 1.2</appear1ch>
	<appear1wr>MT 1.3</appear1wr>
	<conflict></conflict>
	<leadrel>Self</leadrel>
	<bodytyp>average height, average build</bodytyp>
	<age>40 (2017)</age>
	<skin>tanned</skin>
	<eyes>green, hard</eyes>
	<hair>brown</hair>
	<dmarks>star-shaped birthmark on his chin</dmarks>
	<dress>always seen in a blue suit and tie</dress>
	<attposs>carries a briefcase</attposs>
	<asmell>New Spice cologne</asmell>
	<personality>easy-going</personality>
	<speech></speech>
	<formocc><pos>Office Drone</pos></formocc>
	<currocc><pos>Office Manager</pos></currocc>
	<strength>pattern recognition</strength>
	<weak>gambling</weak>
	<mole>None (Lead)</mole>
	<hobby>reading, fantasy football</hobby>
	<misc></misc>
	<ethnic>mixed</ethnic>
	<origin>Florida</origin>
	<backstory></backstory>
	<residence>a small apartment on 15th street</residence>
	<minchar>brother</minchar>
	<talent>drawing</talent>
	<abil></abil>
	<sgoal>To find the lost sword Excalibur</sgoal>
	<other></other>
	<relat>
		<related>Jane Doe</related>
		<relation>Wife</relation>
		<file>doe-jane</file>
		<events>
			<mstone>
				<date>2005/1/2b</date>
				<event>Married</event>
			</mstone>
			<mstone>
				<date>2004/6/1b</date>
				<event>First date</event>
			</mstone>
		</events>
		<rtype>fam</rtype>
		<cat>person</cat>
	</relat>
	<relat>
		<related>Jim Smith</related>
		<relation>Friend</relation>
		<file>smitjim</file>
		<rtype>friend</rtype>
		<cat>person</cat>
	</relat>
	<relat>
		<related>James Noseworthy</related>
		<relation>Boss</relation>
		<file>nosejame</file>
		<rtype>work</rtype>
		<cat>person</cat>
		<realm>ThisCorp</realm>
	</relat>
	<relat>
		<related>Sam Nohbody</related>
		<relation>Subordinate</relation>
		<file>nohbsamu</file>
		<events>
			<mstone>
				<date>2001/3/5b</date>
				<event>Assigned</event>
			</mstone>
			<mstone>
				<date>2002/10/22b</date>
				<event>Promoted</event>
			</mstone>
		</events>
		<rtype>work</rtype>
		<cat>person</cat>
		<realm>ThisCorp</realm>
	</relat>
	<update>09/06/09b</update>
</person>
