=== over2sd/minette/dtd/place.dtd
<!ELEMENT place ( commonname?, name?, start?, scue?, end?, ecue?, stories?, mention?, desc?, address?, loc?, locfile?, state?, statefile?, note*, relat*, update? ) >
<!ELEMENT address ( #PCDATA )>
<!ELEMENT name ( #PCDATA )>
<!ELEMENT start ( #PCDATA )>
<!ELEMENT scue ( #PCDATA )>
<!ELEMENT end ( #PCDATA )>
<!ELEMENT ecue ( #PCDATA )>
<!ELEMENT stories ( #PCDATA )>
<!ELEMENT mention ( #PCDATA )>
<!ELEMENT desc ( #PCDATA )>
<!ELEMENT loc ( #PCDATA )>
<!ELEMENT locfile ( #PCDATA )>
<!ELEMENT state ( #PCDATA )>
<!ELEMENT statefile ( #PCDATA )>
<!ELEMENT note ( content, date )>
<!ELEMENT commonname ( #PCDATA )>
<!ELEMENT relat ( related, relation, file?, rtype, events*, cat ) >
<!ELEMENT cat ( #CDATA ) >
<!ELEMENT rtype ( #CDATA ) >
<!ELEMENT related ( #PCDATA )>
<!ELEMENT relation ( #PCDATA ) >
<!ELEMENT file ( #PCDATA ) >
<!ELEMENT events ( mstone* ) >
<!ELEMENT mstone ( date, event, type? ) >
<!ELEMENT event ( #PCDATA ) >
<!ELEMENT date ( #PCDATA ) >
<!ELEMENT type ( #PCDATA ) >
<!ELEMENT update ( #PCDATA )>

=== over2sd/minette/realms/example/cafe01.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/home/skreyola/wri/fic/cur/chardb/py/xsl/place.xsl"?>
<!DOCTYPE person SYSTEM "place.dtd">
<place>
	<commonname>Anyville: Colored Animal Cafe</commonname>
	<name>The Colored Animal Cafe</name>
	<start>2012/03/23b</start>
	<scue>Built</scue>
	<stories>eg02</stories>
	<mention>EG: 1.1</mention>
	<desc>A nice little cafe with tables on the sidewalk. The sign shows a colored animal.</desc>
	<address>123 Fourth Ave.</address>
	<loc>Anyville</loc>
	<locfile>anyville</locfile>
	<state>Confusion</state>
	<statefile>s-co</statefile>
	<update>12/04/10b</update>
</place>
